name: Build FreeBSD Binary

on:
  push:
    tags:
      - 'v0.10.0'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: false
        default: 'v0.10.0'

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - name: 显示工作流信息
        run: |
          echo "当前触发事件: ${{ github.event_name }}"
          echo "当前标签: ${{ github.ref_name }}"
          echo "当前SHA: ${{ github.sha }}"

      - name: 检查标签是否存在
        run: |
          git fetch --tags
          git tag | grep -q "${{ github.event.inputs.tag || github.ref_name }}"
          if [ $? -eq 0 ]; then
            echo "标签存在"
          else
            echo "错误: 标签不存在于本地仓库"
            exit 1
          fi

      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref_name }}
          fetch-depth: 0
          persist-credentials: false
          lfs: true

      - name: 环境诊断
        run: |
          env
          git status
          git branch -a
          git tag -l

      - name: 显示检出信息
        run: |
          echo "当前分支: $(git rev-parse --abbrev-ref HEAD)"
          echo "当前提交: $(git rev-parse HEAD)"
          echo "工作目录内容:"
          ls -la

      - name: 设置FreeBSD环境并构建
        uses: vmactions/freebsd-vm@v1
        with:
          release: '14.0'
          usesh: true
          sync: rsync
          prepare: |
            pkg update -f
            pkg install -y go gcc node npm git tar bash
            go version
            gcc --version
            node --version
            npm --version
          run: |
            pwd
            ls -la
            if [ ! -f ./build.sh ]; then
              echo "错误: 找不到构建脚本 build.sh"
              exit 1
            fi
            chmod +x ./build.sh
            echo "开始构建后端..."
            ./build.sh backend --no-lint --no-test
            if [ $? -ne 0 ]; then
              echo "错误: 后端构建失败"
              exit 1
            fi
            echo "开始构建前端..."
            ./build.sh frontend --no-lint --no-test
            if [ $? -ne 0 ]; then
              echo "错误: 前端构建失败"
              exit 1
            fi
            echo "开始打包文件..."
            ./build.sh package -o ezbookkeeping-freebsd.tar.gz
            if [ $? -ne 0 ]; then
              echo "错误: 打包失败"
              exit 1
            fi
            echo "构建结果:"
            ls -lh ezbookkeeping-freebsd.tar.gz

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: ezbookkeeping-freebsd
          path: ezbookkeeping-freebsd.tar.gz
          retention-days: 30

      - name: 构建失败通知
        if: failure()
        run: |
          echo "构建失败，请检查日志了解详情"
